### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by moggers87** [justinmayer/django-elevate#4]
Fairly simple to do.

In fact, I already have a branch: https://github.com/moggers87/django-elevate/tree/django-2.0

However, that branch sits on top of PR #3 so I'll wait until that has been merged and then rebase it.

**Comment by justinmayer** [comment]
The dependent PR has been merged, so please feel free to proceed. Looking forward to supporting Django 2.0.  🚀

**Comment by galeo** [comment]
Is there a plan to release a new version?

**Comment by justinmayer** [comment]
@galeo: Yes. I don't have a definitive time-frame, but it should be soon.

**Comment by galeo** [comment]
Thanks!

**Comment by justinmayer** [comment]
v1.0.0 has been released, containing support for Django 2.0. Thanks again to @moggers87 for making that possible! ✨  https://twitter.com/jmayer/status/1011328942958088192
